### ISSUE TITLE
Thanks for your contribution to this environment!

### ISSUE THREAD

**Issue by TianhongDai** [IanYangChina/pybullet_multigoal_gym#1]
Hi,

Thanks for your effort to build up this environment for those who want to do research on the goal-conditional RL but cannot access to the MuJoCo license easily. I hope more and more people can join this community to develop it better! 

Best Regards

**Comment by IanYangChina** [comment]
> Hi,
> 
> Thanks for your effort to build up this environment for those who want to do research on the goal-conditional RL but cannot access to the MuJoCo license easily. I hope more and more people can join this community to develop it better!
> 
> Best Regards

I'm glad you find it useful :)
