### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'task_decomposition'

### ISSUE THREAD

**Issue by learningxiaobai** [IanYangChina/pybullet_multigoal_gym#3]
hello，when i try your Try it out，
i met this problem， do you know why？

**Comment by learningxiaobai** [comment]
there is something wrong with this code：
 File "C:/shiyan/pybullet_multigoal_gym-master/pybullet_multigoal_gym/test/multigoal/gym_image_obs_test.py", line 41, in <module>
    num_goals_to_generate=90)

**Comment by IanYangChina** [comment]
Hi, thanks for the report! This is caused by a small bug in the release version, I have fixed it previously. If you clone and install the newest version, the problem should go away :)
```
git clone https://github.com/IanYangChina/pybullet_multigoal_gym
cd pybullet_multigoal_gym
python -m pip install
python test/multigoal/gym_image_obs_test.py
```

If you are using PyCharm, it's also convenient to simply run the gym_image_obs_test.py script from the IDE, after you install the package with pip.

It works for me, hope it works for you :)

**Comment by IanYangChina** [comment]
Also, you can simply download and install the [v1.1 release](https://github.com/IanYangChina/pybullet_multigoal_gym/releases/tag/v1.1) :)

**Comment by learningxiaobai** [comment]
> Also, you can simply download and install the [v1.1 release](https://github.com/IanYangChina/pybullet_multigoal_gym/releases/tag/v1.1) :)

hello，i still met this problem ：Traceback (most recent call last):
  File "C:/shiyan/pybullet_multigoal_gym-1.1/pybullet_multigoal_gym/test/multigoal/gym_image_obs_test.py", line 41, in <module>
    num_goals_to_generate=90)

and this problem when i ran hierarchical_gym_test.py： File "C:/shiyan/pybullet_multigoal_gym-1.1/pybullet_multigoal_gym/test/multigoal/hierarchical_gym_test.py", line 7, in <module>
    env = pmg.make('KukaParallelGripHierPickAndPlaceSparseImageObsEnv-v0')
 
other test ran well.

by the way ,i use the pycharm and have pip install  related packages.

**Comment by IanYangChina** [comment]
> > Also, you can simply download and install the [v1.1 release](https://github.com/IanYangChina/pybullet_multigoal_gym/releases/tag/v1.1) :)
> 
> hello，i still met this problem ：Traceback (most recent call last):
> File "C:/shiyan/pybullet_multigoal_gym-1.1/pybullet_multigoal_gym/test/multigoal/gym_image_obs_test.py", line 41, in
> num_goals_to_generate=90)
> 
> and this problem when i ran hierarchical_gym_test.py： File "C:/shiyan/pybullet_multigoal_gym-1.1/pybullet_multigoal_gym/test/multigoal/hierarchical_gym_test.py", line 7, in
> env = pmg.make('KukaParallelGripHierPickAndPlaceSparseImageObsEnv-v0')
> 
> other test ran well.
> 
> by the way ,i use the pycharm and have pip install related packages.

Hi, thanks for the report.
The hierarchical tasks are not ready to run at the moment cuz I don't have enough time to deal with them.
You can play with non-hierarchical tasks as you like :)
I may have time to test and fix the hierarchical tasks next month, so you may need to wait for it if you specifically want to use it.
