### ISSUE TITLE
Several minor issues

### ISSUE THREAD

**Issue by SamNPowers** [IanYangChina/pybullet_multigoal_gym#5]
Hi, thanks for the helpful repo! It's exactly what I was looking for.

I'm encountering a few issues though. 

1. The examples define observation_cam_id as an integer (e.g. 0), but https://github.com/IanYangChina/pybullet_multigoal_gym/blob/c5a90680702f17734cf1c9b1f797b8ac9846810e/pybullet_multigoal_gym/__init__.py#L116 assumes it's a list. (Based on the default value assigned at the beginning of the function it should be, e.g. [0])
2. obs_dict as used https://github.com/IanYangChina/pybullet_multigoal_gym/blob/c5a90680702f17734cf1c9b1f797b8ac9846810e/pybullet_multigoal_gym/envs/base_envs/kuka_multi_step_base_env.py#L341 isn't defined before it is used
3. Joints as used here https://github.com/IanYangChina/pybullet_multigoal_gym/blob/c5a90680702f17734cf1c9b1f797b8ac9846810e/pybullet_multigoal_gym/robots/kuka.py#L341 expect 2 outputs, but get_state() returns 3 (x, vx, fx). 
4. Observation isn't defined when it is used here: https://github.com/IanYangChina/pybullet_multigoal_gym/blob/c5a90680702f17734cf1c9b1f797b8ac9846810e/pybullet_multigoal_gym/envs/base_envs/kuka_multi_step_base_env.py#L347

And likely more; I stopped here as this is more errors than I expect to find. Is there a different version of the codebase I should be using? Am I missing something more obvious?

Thanks!

**Comment by IanYangChina** [comment]
Hi, will look into them. These are probably caused by my experimental codes. I have been doing some tinkerings and did not clean up things properly. I would suggest you use the released version, probably less or no errors. Are you using the master branch?

**Comment by SamNPowers** [comment]
I am on master. I'll use the latest released version instead for now (v1.2 I believe?).

Thanks!

**Comment by IanYangChina** [comment]
Hi, I fixed all the bugs and released a new version (v1.3). Or you can just keep using the master branch now. Thanks.
