### ISSUE TITLE
Where does the max_episode_steps make the time_done True

### ISSUE THREAD

**Issue by Pingcheng-Jian** [IanYangChina/pybullet_multigoal_gym#7]
Hi,

The env.step(action) returns a "time_done" variable and it turns True when the robot has moved for 50 steps.

However, in the "step" function in the pybullet_multigoal_gym/envs/base_envs/base_env.py file, this variable is always set to be False.

Could you please let me know where you use the "max_episode_steps" to turn the "time_done" to be True?

Thanks a lot,
Pingcheng

**Comment by IanYangChina** [comment]
Hi, this is done by the OpenAIGym timelimit wrapper. 
https://github.com/openai/gym/blob/0.25.2/gym/wrappers/time_limit.py
