### ISSUE TITLE
import pybullet_multigoal_gym as pmg ，pybullet_multigoal_gym is None

### ISSUE THREAD

**Issue by letgo-hub** [IanYangChina/pybullet_multigoal_gym#8]
Install the environment according to requirements. txt, but an error is reported
env = pmg.make_env(task='pick_and_place',
AttributeError: module 'pybullet_multigoal_gym' has no attribute 'make_env'

**Comment by IanYangChina** [comment]
Hi, could you give a full description of how to reproduce the issue?

**Comment by IanYangChina** [comment]
I'm closing this issue I haven't heard any update for a while.
